package guiController;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.stage.Stage;
import javafx.scene.control.ComboBox;

import javafx.scene.control.DatePicker;

public class BookComputerStationController extends Controller implements Initializable {
	@FXML
	private Label l_station;
	@FXML
	private DatePicker dp_occpuy_date;
	@FXML
	private ComboBox cb_occupy_h_s;
	@FXML
	private ComboBox cb_occupy_m_s;
	@FXML
	private ComboBox cb_occupy_h_e;
	@FXML
	private ComboBox cb_occupy_m_e;
	@FXML
	private Button b_ok;
	@FXML
	private Button b_cancel;
	
	public BookComputerStationController(ScreenController screen_controller) {
		super(screen_controller);
		// TODO Auto-generated constructor stub
	}

	// Event Listener on Button[#b_ok].onAction
	@FXML
	public void book(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#b_cancel].onAction
	@FXML
	public void quit(ActionEvent event) {
		Stage stage = (Stage) b_cancel.getScene().getWindow();
		stage.close();
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
