package guiController;

import Area.Zone;
import User.User;
import Area.Building;
import Area.Classroom;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.scene.control.MenuItem;
import javafx.scene.control.Tab;
import javafx.scene.control.ComboBox;


public class MainController extends Controller implements Initializable {
	@FXML
	private MenuItem MenuBarProfile;
	@FXML
	private MenuItem MenuBarLogOut;
	@FXML
	private MenuItem MenuBarExit;
	@FXML
	private TextField searchBar;
	@FXML
	private ComboBox<Zone> ComboZone;
	@FXML
	private ComboBox<Building> ComboBuilding;
	@FXML
	private ComboBox<Building> ComboRoom;
	@FXML
	private Button ButtonAddComputerStation;
	@FXML
	private Tab materialTab;
	@FXML
	private Tab teacherTab;

		
	private User main_user;
	
	
	public MainController(ScreenController screen_controller) {
		super(screen_controller);
	}
	
	public void setUser(User u) {
		this.main_user = u;
		System.out.println(this.main_user.toString());
		
		// Hide / Show teacher tab depending on user rights 
		if(main_user.isTeacher())
			this.teacherTab.setDisable(true);
	}

	// Event Listener on MenuItem[#MenuBarProfile].onAction
	@FXML
	public void seeProfile(ActionEvent event) throws IOException {
		
		FXMLLoader detail_user_loader = new FXMLLoader();
		detail_user_loader.setLocation(getClass().getResource("/application/detail_user.fxml"));
		detail_user_loader.setController(new DetailUserController(this.screen_controller, main_user));
		
		Scene detail_user_scene = new Scene(detail_user_loader.load());
		Stage stage = new Stage();
        stage.setTitle("My New Stage Title");
        stage.setScene(detail_user_scene);
        stage.show();
	}
	
	// Event Listener on MenuItem[#MenuBArLogOut].onAction
	@FXML
	public void logOut(ActionEvent event) {
		this.screen_controller.activate("connexion");
		this.main_user = null;
	}
	
	// Event Listener on MenuItem[#MenuBarExit].onAction
	@FXML
	public void exitApp(ActionEvent event) {
		System.exit(0);
	}
	
	// Event Listener on ComboBox[#ComboZone].onAction
	@FXML
	public void setBatimentChoice(ActionEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on ComboBox[#ComboBuildings].onAction
	@FXML
	public void setClassrooms(ActionEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#ButtonAddComputerStation].onAction
	@FXML
	public void addComputerStation(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {		
		//TODO set ITManagementDB as model in order to send request to DB as this moment to complete the scheme
		Zone sevenans = new Zone(1, "Sevenans");
		Zone belfort = new Zone(2, "Belfort");
		Zone montbeliard = new Zone(3, "Montbéliard");
		
		ComboZone.getItems().addAll(sevenans, belfort, montbeliard);
		
	}
}
